### ISSUE TITLE
Nexus Browser: Feature request to allow https

### ISSUE THREAD

**Issue by dtarnawsky** [ionic-team/vscode-extension#104]
Allow using https with Ionic Server (and a self signed untrusted certificate).

**Comment by lukasreiner** [comment]
Thanks for the feature request. This is important because all apps that use crypto.js need to use https since on http window.crypto is undefined for security reasons. 

So `set HTTPS=true&&ionic serve` won't work at the moment because we can't bypass this warning like we can do in all other browsers.

![image](https://user-images.githubusercontent.com/30616142/230398918-2f04a7e0-b11e-4d43-bc6b-35dc12b828b5.jpeg)

**Comment by dtarnawsky** [comment]
Version 1.35 of the extension supports Nexus Browser working with https. Nexus Browser 1.7 (build 18) have been submitted to the stores and they will support https if the certificate is trusted. You can trust a certificate by following the instructions when you check the "Use HTTPS" option from Settings.

Note: Although it is possible to trust untrusted certificates both the App Store and Play Store reject app submissions that allow this. So, you must go through the process of installing a certificate on the device.

I'll close out this issue when the versions have been approved in the App Store and Play Store
