### ISSUE TITLE
Error mv: cannot stat 'my-test-app/{,.[^.]}*': No such file or directory when creating project using vscode extension

### ISSUE THREAD

**Issue by Solarinius** [ionic-team/vscode-extension#123]
1. start vscode
2. open ionic extension tab
3. click New Project
4. type in an internal name for application
5. hit enter

Expected result: app is created and success message is shown

Actual result: Error mv: cannot stat (as seen in attached screenshot)
![ionicerror](https://github.com/ionic-team/vscode-extension/assets/11800145/bae02811-167f-49b2-90c8-9d386f774f31)

System: Ubuntu 20.04
VSCode info: 
```
Version: 1.79.2
Commit: 695af097c7bd098fbf017ce3ac85e09bbc5dda06
Date: 2023-06-14T08:59:55.818Z
Electron: 22.5.7
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Linux x64 5.15.0-75-generic snap
```
Ionic Extension version: v1.45.5

**Comment by dtarnawsky** [comment]
Just an FYI: we haven't forgotten about this reported issue. The "new project" UI design is being reworked and may take a bit of time to release. Also, we've been targeting/testing with Mac and Windows and haven't been testing with Ubuntu/Linux flavors due to their uniqueness (and the low number of users using the platform for mobile dev). Stay tuned...

**Comment by dtarnawsky** [comment]
Hey @Solarinius,

The VS Code extension has been updated to 1.47.1 and it includes a brand new "new project" experience that no longer needs the commands to `vm` and `rmdir`. Can you try this out and let me know if it resolves this issue on Ubuntu?

**Comment by Solarinius** [comment]
Looks like it's resolved now. Project had been set up nicely without any
warnings or anything. Thanks!
