### ISSUE TITLE
Inconsistent behavior of the ionic wizard depending on the active directory

### ISSUE THREAD

**Issue by oweitman** [ionic-team/vscode-extension#130]
I was able to perceive 2 behaviors

**1) opening vs code in an newly created empty directory for example ./test**
-> after clicking on the ionic extension icon the wizard opens automaticly, you enter a project name and enter the other options and click "create project"
**result** -> the wizard creates a new project under the selected one for example in the directory ./test/my Project
**expected result**: the wizard creates a new project in the selected folder

**2) opening vs code in an existing directory in my case the root directory of all my vs code projects: ./vscode**
-> after clicking on the ionic extension icon the wizard doesnt opens 
**result**: in my case it recognize a project below this root directory that doesnt have to do with ionic. i cant trigger the wizard 
**expected result**: if the wizard didnt recognize any ionic project in the selected folder (and not below in any directory) the wizard opens, i can enter the new project name and the other options and the wizard create all needed stuff in the newly created directory below the selected and switch automaticly to this folder after finishing the scaffolding process

Recommendation: 
sometimes too much automatic and magic isn't helpful. maybe you can just place the command "ionic wizard" in ionic explorer

**Comment by dtarnawsky** [comment]
I've added a feature into v1.52 to allow you to only manually create new projects. Just check the option in "`Settings`" > "`Advanced`" > `"Manual New Projects"`. You will then only get the new project dialog when you select "Ionic: New Project" from the command palette.

Also, there were fixes for the New Project dialog appearing consistently in 1.49.2 and 1.50.0. I'll close out this ticket as you should be seeing consistent behavior or choosing the path of empty directories if the workspace is one, or choosing the default project path otherwise.
