### ISSUE TITLE
cant't debug

### ISSUE THREAD

**Issue by invalidtruck** [ionic-team/vscode-extension#146]
Hi, i have this problem

![image](https://github.com/ionic-team/vscode-extension/assets/11415241/815de0d2-737f-49ef-96ff-4e740ff249a7)

there's no debug! 

after generate build for android , i lose debug option
and each click on debug section this toast appear

 
![image](https://github.com/ionic-team/vscode-extension/assets/11415241/37b96fde-1da6-41c2-904a-7ee0ccd1bd1e)

i reinstalled the extension but this not fix the problem

sorry for my bad english

**Comment by dtarnawsky** [comment]
HI David,

Your Android Studio installation cannot be found by the Extension. 

If you have not installed Android Studio yet then please install it from [here](https://developer.android.com/studio).
If you have it installed it you may need to update it to the latest.

If it is installed but the extension still shows an error trying to run `adb` (Android Debug Bridge which is installed with Android Studio) then you must have a custom place you installed Android Studio and need to specify where `adb` is installed. You can do this by clicking `Settings` > `Advanced` and specifying the path to the `adb` file.

**Comment by otiv33** [comment]
I had the same issue. I didn't have a custom install of android studio but still this issue was present. Tested if I can run `adb` in terminal, and the command was not recognized.

For my windows machine I fixed it by adding `C:\Users\USER\AppData\Local\Android\Sdk\platform-tools` to  environment path. This folder is where the `adb` cli tool resides. Restarted VS code and voila it worked. 

Thank you @dtarnawsky for the helpful comment.

**Comment by piotr-cz** [comment]
On Windows, it extension should try to start `%ANDROID_HOME%\platform-tools\adb.exe` or `ANDROID_SDK_ROOT\platform-tools\adb.exe`.

Unfortunately it's environment variables are not expanded and you have to set full path in extension settings.

**Comment by dtarnawsky** [comment]
@piotr-cz Version 1.83 added a fix to find adb. This should now be working.
