### ISSUE TITLE
Handle Old Vue projects

### ISSUE THREAD

**Issue by dtarnawsky** [ionic-team/vscode-extension#40]
Vue projects often have a build and serve script in package.json but because they do not have ionic:serve and ionic:build then Ionic CLI commands will fail. To better support these have the extension create the ionic:serve and ionic:build script commands if serve and build exists.

> is there some magic required to get the extension to work on older project?
> 
> When i run it i am getting errors on vue project missing ionic:serve command and then next i get errors with the launch.json not configured properly

**Comment by Lexpeartha** [comment]
I think it would also be really helpful to create a list of guidelines or additional customisations, so other technologies built a top of ionic can know how to benefit from working properly with the extension. For example new Vite projects have `dev` script instead of `serve`(in addition to `preview`) which was the case with vue-cli. I've tried using extension with nuxt and `nuxt-ionic` module, but it didn't work really well, mostly because extension assumes certain project structures and usage of vue-cli (which is in Vue community getting left behind in the shadow of the better tooling). There's also open issue about it on module repo danielroe/nuxt-ionic#24

@dtarnawsky is flexibility for more modern Vue projects something your team considered?

**Comment by dtarnawsky** [comment]
Hi @Lexpeartha,

I just released 1.9.3 of the extension which adds automatic detection of Vite-based projects which have the convention of using `dev`, `preview`, and `build` as the default names for scripts.

Handling of projects that were not built from Ionic starters (which have a type of `vue`, `angular` or `react`) can get a little tricky. The usual route is using the command `ionic init` which will create an `ionic.config.json` file with a type of `custom`. At that point, your project doesn't have enough cues for us to know how it might work. Also, as your project is custom it isn't really being operated on by the Ionic CLI and because Capacitor isn't introduced yet it isn't using the Capacitor CLI either. So, this is where the VS Code extension tries to take best-guess effort at what you are doing.

For Vue projects in particular there has been a lot of fracturing of how Vue should be used. Vite is getting popular and when it reaches a tipping point it's likely that the Ionic Starter for Vue will be Vite based. It is definitely something the team is considering.

For now, I'll close out this issue as the Extension has support to detect and work with different Vue-based projects and will add an `ionic:build` and `ionic:serve` script to minimally support most Vue projects. If you run into any particular issues feel free to open another issue.
