### ISSUE TITLE
Extension showing subfolder only

### ISSUE THREAD

**Issue by cbetz** [ionic-team/vscode-extension#47]
We have a project that is structured like this:

root
|-- android
|-- functions
|-- |-- src
|-- |-- package.json
|-- ios
|-- src
|-- ...
|-- package.json

The Ionic project is the root project (with the `package.json` in the root). The `functions` subfolder is for Firebase functions (not an Ionic project). The extension shows only the `functions` subfolder:

<img width="253" alt="image" src="https://user-images.githubusercontent.com/458549/171188935-65c8080d-73d7-4bef-b92e-fc31376dfc87.png">

Is there a way to "force" the extension to map to the root folder instead?

**Comment by dtarnawsky** [comment]
Hi @cbetz,

Thanks for the bug report. This should now be fixed in 1.8.5! Theres a new rule that if non of the subfolders with package.jsons contain an Ionic app (@ionic/vue,react or angular, or @angular/core) then it will treat the folder structure as a single repo rather than mono repo.

Hopefully this fixes your problem.

**Comment by cbetz** [comment]
Thank you for the quick reply and turnaround on this! Verified it is working with 1.8.5. Awesome extension!

**Comment by cbleu** [comment]
Hi, i have exactly the same problem with an ionic/angular project where i have a ./functions sub-project for Firebase-functions.

I have the latest ionic (v1.27.1), vscode(v1.76.0) versions.

Thanks for you help or advices!

best regards,
cesar

**Comment by dtarnawsky** [comment]
Hi @cbleu , This is a closed issue, but if you can provide a sample project with this problem then I can help?
