### ISSUE TITLE
App not working and Remote Logging not showing anything

### ISSUE THREAD

**Issue by ghost** [ionic-team/vscode-extension#94]
My App is failing when I open it in Nexus and try to login to my server.  I do not know what the error is - is it likely to be CORS or something?  I have Remote Logging switched on but I don't see any console logs coming back to VS Code anywhere?

Ionic Info:

Ionic:

   Ionic CLI                     : 6.20.5 (/Users/xxx/.nvm/versions/node/v18.12.0/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.5.4
   @angular-devkit/build-angular : 15.1.2
   @angular-devkit/schematics    : 15.1.2
   @angular/cli                  : 15.1.2
   @ionic/angular-toolkit        : 8.0.0

Capacitor:

   Capacitor CLI      : 4.6.3
   @capacitor/android : 4.6.3
   @capacitor/core    : 4.6.3
   @capacitor/ios     : 4.6.3

Utility:

   cordova-res : not installed globally
   native-run  : 1.7.1

System:

   NodeJS : v18.12.0 (/Users/xxx.nvm/versions/node/v18.12.0/bin/node)
   npm    : 8.19.2
   OS     : macOS

**Comment by dtarnawsky** [comment]
Hey Richard,

The problem is likely going to be differences in plugins. Take a look at [capacitor.nexusbrowser.com](https://capacitor.nexusbrowser.com) and scroll down to the plugin section and see if there are some plugins that you have that are different.

I'm currently working on 2 features that are going to help out with the in the future:
- The extension will check the list of plugins and show which plugins are likely to cause problems
- The Nexus app will send JS and Native errors to the extension via remote logging so you can see which plugin is causing an issue

In the meantime though I would suggest sending over your package.json and I can take a look. You can send to [email redacted]

**Comment by ghost** [comment]
Thank you @dtarnawsky - will send it over

**Comment by dtarnawsky** [comment]
Hey @richardkshergold,

Here's the message you'll get in the next version of the extension (with your particular project):

> Nexus Browser does not have the following plugins: @capacitor-community/file-opener, @capacitor-community/http, @capacitor/push-notifications, @capawesome/capacitor-badge, capacitor-secure-storage-plugin, cordova-plugin-calendar, cordova-plugin-file-transfer, cordova-plugin-fingerprint-aio, cordova-plugin-market

One of these plugins will be erroring on startup. I'll be putting together an update to the app that sends native errors back to vs code and it should reveal which one is throwing an error. You could attempt to put try/catch calls around any native calls in your app for these. My guess is that it is most likely `@capacitor-community/http` and that you could fix the problem by switching to [Capacitor's HTTP built in plugin](https://capacitorjs.com/docs/apis/http).

**Comment by dtarnawsky** [comment]
Hey @richardkshergold,

The extension should now be reporting any plugins your project has that the Nexus Browser does not. It should also be sending remote logs to VS Code and will report an error for any plugins that your app calls that do not exist. For any of those that you really want in Nexus Browser then please add a suggestion to: https://github.com/ionic-team/vscode-ionic/issues/148

Let me know if this is working for you (or at least working as expected).
