### ISSUE TITLE
Extension won't work on pure capacitor project

### ISSUE THREAD

**Issue by riderx** [ionic-team/vscode-extension#95]
<img width="489" alt="CleanShot 2023-03-06 at 15 41 43@2x" src="https://user-images.githubusercontent.com/4084527/223142988-d66128a4-e922-479b-8b93-4567e36696b9.png">

the extension keep tell me to add ionic integration and when i click it say it cannot read non JSON file

**Comment by dtarnawsky** [comment]
Is your project something that you can share? If so, you could send a link to damian at ionic dot io and I can take a look

**Comment by riderx** [comment]
yes it's open source : https://github.com/Cap-go/capgo

**Comment by dtarnawsky** [comment]
Thanks for the project. A new version of the extension has been released to detect your project type (1.28). There is one thing that you may need to do after installing 1.28 and that is to delete `ionic.config.json` and let the extension recreate it when you click the build command - the reason is that the project is actually "custom" instead of "vue" and you have `capacitor` as an integration. When you get the new version it should walk you through the steps to fix the project too.

**Comment by riderx** [comment]
Thanks a lot for the prompt fix, you rox !

i was wondering if project without ionic config could be considered as custom by default?

otherwise thanks again man

**Comment by dtarnawsky** [comment]
If the ionic config is missing the Ionic CLI will consider it as a problem and abort with an error, asking you to run `ionic init`. The extension however inspects logs from the CLI and will choose to init the project as `custom` if it can't see that your project is based on `@ionic/angular`, `@ionic/vue` or `@ionic/react`.
